// Controlled DOM + actual frontend API + local HTTP proxy + FastAPI integration.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import vm from 'node:vm';
const require = createRequire(import.meta.url);
const {JSDOM} = require(process.env.JSDOM_PATH);
const root = process.cwd();
const origin = process.env.CAMPAIGN_TEST_ORIGIN;
const realFetch = globalThis.fetch;
const requests = [];
let fault = null;
let pause = null;
globalThis.fetch = async (url, options={}) => {
  const path = new URL(url).pathname + new URL(url).search;
  if (!path.startsWith('/api/v1/campanias')) {
    return Response.json({items:path==='/api/v1/colegios'?[{_id:'huayquique-test',nombre:'Huayquique PRUEBA',comuna:'Huayquique'}]:[]});
  }
  const record = {path, method:options.method||'GET', headers:options.headers, body:options.body&&JSON.parse(options.body)};
  requests.push(record);
  if (pause && record.method !== 'GET') await pause;
  let response;
  if (fault && record.method !== 'GET') {response = Response.json(fault,{status:422});fault=null;}
  else response = await realFetch(origin+path, options);
  record.status = response.status;
  record.response = await response.clone().json();
  return response;
};
const api = await import(pathToFileURL(root+'/frontend2/api.js'));
await assert.rejects(api.finalizarCampania('camp_dev_huayquique',{fecha_cosecha_real:'2026-10-01'}), error=>error.status===422&&Boolean(error.fields.resultado_final)&&Boolean(error.fields.confirmar)&&!error.message.includes('Field required'));
const html = readFileSync(root+'/frontend2/index.html','utf8');
const css = readFileSync(root+'/frontend2/campaigns.css','utf8');
const dom = new JSDOM(html,{url:origin,runScripts:'outside-only',pretendToBeVisual:true});
const {window} = dom;
const style=window.document.createElement('style');style.textContent=css;window.document.head.append(style);
window.api = api;
window.console = console;
const source = readFileSync(root+'/frontend2/app.js','utf8').replace(/^import \{([^}]+)\} from [^;]+;/,'const {$1} = api;');
vm.runInContext(source,dom.getInternalVMContext());
const $ = selector=>window.document.querySelector(selector);
const waitFor = async (predicate,label)=>{
  const until=Date.now()+8000;
  while(!predicate()){if(Date.now()>until)throw Error('Timeout: '+label+'; '+$('#campaign-status').textContent);await new Promise(r=>setTimeout(r,15));}
};
const submit = selector=>$(selector).dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
const writes = ()=>requests.filter(r=>r.method!=='GET');
await new Promise(r=>setTimeout(r,30));
$('[data-tab="campaigns"]').click();
await waitFor(()=>$('#campaign-edit'),'campaña activa');
assert.equal($('#campaign-college').value,'huayquique-test');
assert.equal($('#campaign-edit').disabled,false);
assert.notEqual(window.getComputedStyle($('#campaign-edit')).display,'none');
assert.equal($('#campaign-edit').closest('[hidden]'),null);
$('#campaign-edit').click();
assert.equal($('#campaign-form').dataset.mode,'edit');
assert.equal($('#campaign-form').closest('[hidden]'),null);
assert.equal($('#campaign-form-title').textContent,'Editar campaña');
assert.equal($('#campaign-submit').textContent,'Guardar cambios');
for(const [id,value] of Object.entries({'name':'PRUEBA Huayquique','crop':'lechuga','sowing':'2026-09-01','estimated':'2026-12-01','notes':'Observación original'}))assert.equal($('#campaign-'+id).value,value);
assert.equal($('#campaign-form [name="colegio_id"]'),null);
assert.equal($('#campaign-form [name="estado"]'),null);
assert.equal($('#campaign-form [name="motivo_correccion"]'),null);
$('#campaign-notes').value='  Observación editada en prueba  ';
fault={detail:[{type:'string_too_long',loc:['body','observaciones'],msg:'String should have at most 2000 characters'}]};
submit('#campaign-form');
await waitFor(()=>!$('#campaign-submit').disabled,'edición rechazada');
assert.equal($('#campaign-form').closest('[hidden]'),null);
assert.equal($('#campaign-notes').value,'  Observación editada en prueba  ');
assert.match($('[data-campaign-error="observaciones"]').textContent,/observaciones/);
submit('#campaign-form');
await waitFor(()=>$('#campaign-status').textContent==='Campaña actualizada correctamente.','edición guardada');
assert.equal(writes().at(-1).method,'PATCH');
assert.equal(writes().at(-1).path,'/api/v1/campanias/camp_dev_huayquique');
assert.deepEqual(writes().at(-1).body,{revision:0,observaciones:'Observación editada en prueba'});
assert.equal(writes().at(-1).headers['Content-Type'],'application/json');
assert.equal(writes().at(-1).status,200);
assert.match($('#campaign-active').textContent,/Observación editada en prueba/);
$('#campaign-edit').click();
assert.equal($('#campaign-notes').value,'Observación editada en prueba');
$('#campaign-form-cancel').click();
$('#campaign-edit').click();$('#campaign-form-cancel').click(); // repeated renders must not add listeners
const before=writes().length;
$('#campaign-finish').click();
assert.equal(writes().length,before);
assert.equal($('#campaign-finish-panel').hidden,false);
submit('#campaign-finish-form');
assert.equal(writes().length,before);
assert.match($('[data-campaign-error="fecha_cosecha_real"]').textContent,/fecha real/);
assert.match($('[data-campaign-error="resultado_final"]').textContent,/resumen/);
$('#campaign-finish-date').value='2026-08-31';$('#campaign-finish-result').value='   ';$('#campaign-finish-confirm').checked=true;
submit('#campaign-finish-form');assert.equal(writes().length,before);
assert.match($('[data-campaign-error="fecha_cosecha_real"]').textContent,/anterior/);
$('#campaign-finish-date').value='2026-10-01';$('#campaign-finish-result').value='  Cosecha de prueba terminada  ';$('#campaign-finish-notes').value='  Sin incidencia  ';
fault={detail:[{type:'missing',loc:['body','resultado_final'],msg:'Field required'},{type:'missing',loc:['body','confirmar'],msg:'Field required'}]};
submit('#campaign-finish-form');
await waitFor(()=>!$('#campaign-finish-submit').disabled,'422 traducido');
assert.equal($('#campaign-finish-panel').hidden,false);
assert.equal($('#campaign-finish-result').value,'  Cosecha de prueba terminada  ');
assert.match($('#campaign-status').textContent,/Debe escribir un resumen/);
assert.match($('[data-campaign-error="confirmar"]').textContent,/confirmar explícitamente/);
assert.ok(!window.document.body.textContent.includes('Field required'));
let release;pause=new Promise(resolve=>release=resolve);
submit('#campaign-finish-form');submit('#campaign-finish-form');
assert.equal($('#campaign-finish-submit').textContent,'Finalizando…');
assert.equal($('#campaign-college').disabled,true);
assert.ok($('#campaign-finish'));
assert.equal(writes().length,before+2);
release();pause=null;
await waitFor(()=>$('#campaign-status').textContent==='Campaña finalizada y trasladada al historial.','finalización guardada');
assert.equal(writes().at(-1).status,200);
assert.equal(writes().at(-1).method,'PUT');
assert.deepEqual(writes().at(-1).body,{fecha_cosecha_real:'2026-10-01',resultado_final:'Cosecha de prueba terminada',observaciones_finales:'Sin incidencia',confirmar:true,revision:1});
assert.equal($('#campaign-finish-panel').hidden,true);
assert.equal($('#campaign-edit'),null);
assert.match($('#campaign-history').textContent,/finalizada/);
assert.equal($('#campaign-count').textContent,'1 campaña');
assert.equal($('#campaign-new-trigger').disabled,false);
assert.equal($('#campaign-college').value,'huayquique-test');
$('#campaign-new-trigger').click();
assert.equal($('#campaign-form').dataset.mode,'create');
assert.equal($('#campaign-crop').value,'');
assert.ok(!window.document.body.textContent.includes('Field required'));
console.log(JSON.stringify({result:'PASS',requests},null,2));
window.close();
