export const localidades={
colchane:{nombre:"Colchane",colegio:"Colegio de Colchane",icono:"🏔️",tipo:"Activo"},camina:{nombre:"Camiña",colegio:"Colegio de Camiña",icono:"🌄",tipo:"Activo"},huara:{nombre:"Huara",colegio:"Colegio de Huara",icono:"☀️",tipo:"Activo"},"la-tirana":{nombre:"La Tirana",colegio:"Colegio de La Tirana",icono:"⛪",tipo:"Activo"},pica:{nombre:"Pica",colegio:"Colegio de Pica",icono:"🌳",tipo:"Activo"},huayquique:{nombre:"Huayquique",colegio:"Colegio Piloto de Huayquique",icono:"🌊",tipo:"Piloto"}};
export const sensores={
temperatura_aire:{nombre:"Temperatura del aire",valor:24.6,unidad:"°C",icono:"☀️",color:"#ef5a19",rango:"18 a 28 °C",ideal:[18,28],min:10,max:35,texto:"Nos cuenta cuánto calor siente la planta sobre la tierra.",datos:[24,25,26,23,21,22,24],hotspot:"air",grupo:"temperatura"},
humedad_aire:{nombre:"Humedad del aire",valor:64.4,unidad:"%",icono:"💧",color:"#128bc7",rango:"50 a 75 %",ideal:[50,75],min:0,max:100,texto:"Mide el agua invisible que viaja en el aire alrededor de las hojas.",datos:[62,66,64,60,56,59,62],hotspot:"humidity",grupo:"humedad"},
humedad_hojas:{nombre:"Humedad de las hojas",valor:11.8,unidad:"%",icono:"🍃",color:"#5da72e",rango:"0 a 20 %",ideal:[0,20],min:0,max:100,texto:"Indica si las hojas permanecen mojadas y necesitan más ventilación.",datos:[10,16,14,12,8,7,10],hotspot:"leaf",grupo:"humedad"},
altura_planta:{nombre:"Altura de la planta",valor:32.8,unidad:"cm",icono:"🌱",color:"#67a82d",rango:"Según etapa",ideal:[15,35],min:0,max:40,texto:"Permite descubrir cuánto ha crecido la planta desde la última medición.",datos:[12,15,18,22,25,29,33],hotspot:"plant",grupo:"crecimiento"},
ph_agua:{nombre:"pH del agua",valor:6.34,unidad:"pH",icono:"🧪",color:"#803b94",rango:"6,0 a 7,0",ideal:[6,7],min:4,max:9,texto:"Nos dice si el agua está equilibrada para que las raíces aprovechen nutrientes.",datos:[6.3,6.7,7,6.8,6.4,6.1,6.3],hotspot:"ph",grupo:"agua"},
sales_agua:{nombre:"Sales del agua",valor:.8,unidad:"mS/cm",icono:"⚛️",color:"#763b91",rango:"0,2 a 1,2 mS/cm",ideal:[.2,1.2],min:0,max:1.5,texto:"Estima la cantidad de sales disueltas en el agua de riego.",datos:[.74,.77,.82,.81,.79,.78,.8],hotspot:"salinity",grupo:"agua"},
temperatura_tierra:{nombre:"Temperatura de la tierra",valor:26.1,unidad:"°C",icono:"♨️",color:"#ef9d00",rango:"18 a 27 °C",ideal:[18,27],min:10,max:35,texto:"Mide el calor en la superficie donde comienza la vida del suelo.",datos:[25,27,28,25,23,24,26],hotspot:"surface",grupo:"temperatura"},
humedad_tierra:{nombre:"Humedad de la tierra",valor:38.1,unidad:"%",icono:"💦",color:"#0b9bc7",rango:"30 a 50 %",ideal:[30,50],min:0,max:100,texto:"Indica cuánta agua está disponible dentro de la tierra para las raíces.",datos:[37,43,50,46,40,35,38],hotspot:"soilMoisture",grupo:"humedad"},
temperatura_bajo_tierra:{nombre:"Temperatura bajo tierra",valor:20.8,unidad:"°C",icono:"🌡️",color:"#2465a8",rango:"16 a 24 °C",ideal:[16,24],min:10,max:35,texto:"Mide la temperatura en la zona protegida donde crecen las raíces.",datos:[20,20.5,21,20.2,19.5,19.7,20.8],hotspot:"soilTemp",grupo:"temperatura"},
temperatura_agua:{label:"Temperatura del agua",nombre:"Temperatura del agua",nombreCompleto:"Temperatura del agua del estanque",valor:null,unidad:"°C",unit:"°C",source:"hanna",field:"temp_avg_c",icono:"💧",color:"#168bb8",rango:"Sin rango definido",ideal:null,min:0,max:40,texto:"Muestra la temperatura promedio diaria del agua del estanque medida por el equipo Hanna.",datos:[],hotspot:null,grupo:"temperatura"},
largo_raiz:{nombre:"Largo de la raíz",valor:18.4,unidad:"cm",icono:"🌿",color:"#6f9c2f",rango:"Según etapa",ideal:[8,22],min:0,max:40,texto:"Ayuda a observar cómo la planta explora la tierra buscando agua y nutrientes.",datos:[8,10,11,13,15,17,18.4],hotspot:"root",grupo:"crecimiento"}};
